baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "chooblarin's blog"

[Params]

  twitter = "chooblarin"
  github = "chooblarin"
  linkedin = "sota-hatakeyama-35bb07120"

  disqus = "chooblarin"

  author = "chooblarin"
