baseurl = "http://chooblarin.github.io/"
languageCode = "en-us"
title = "chooblarin's blog"

[Params]

  twitter = "chooblarin"
  github = "chooblarin"
  linkedin = "sota-hatakeyama-35bb07120"

  disqus = "chooblarin"

  author = "chooblarin"
