baseurl = "http://chooblarin.github.io/"
languageCode = "en-us"
title = "chooblarin's blog"
hasCJKLanguage = true

[Params]

  twitter = "chooblarin"
  github = "chooblarin"
  linkedin = "sota-hatakeyama-35bb07120"

  disqus = "chooblarin"
  ga_api_key = "UA-62520326-2"
  avatar = "/images/kao.png"

  author = "chooblarin"
