name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          yarn
          yarn generate-sitemap
          yarn run build-export
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          branch: gh-pages
          folder: out
          clean: true
